In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])


In [3]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [4]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [5]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [6]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [7]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [8]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [9]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [10]:
transform = lambda x: x[:4].upper()

In [11]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [13]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [14]:
data.index = data.index.map(transform)

In [15]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [16]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [17]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [18]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [19]:
data.rename(index={'OHIO': 'Indiana'}, inplace=True)

In [20]:
data

one  two  three  four
Indiana    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [21]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [22]:
bins = [18, 25, 35, 60, 100]

In [23]:
cats = pd.cut(ages, bins)

In [24]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [25]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [26]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [27]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [28]:
pd.cut(ages, [18, 26, 36, 61, 100], right = False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [29]:
groupnames = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [31]:
cats = pd.cut(ages, bins, labels=groupnames)

In [32]:
pd.value_counts(cats)

Youth         5
MiddleAged    3
YoungAdult    3
Senior        1
dtype: int64

In [33]:
data = np.random.rand(20)

In [34]:
pd.cut(data, 4, precision=2)

[(0.51, 0.76], (0.76, 1.0], (0.76, 1.0], (0.027, 0.27], (0.51, 0.76], ..., (0.51, 0.76], (0.027, 0.27], (0.76, 1.0], (0.027, 0.27], (0.027, 0.27]]
Length: 20
Categories (4, interval[float64]): [(0.027, 0.27] < (0.27, 0.51] < (0.51, 0.76] < (0.76, 1.0]]

In [40]:
data = np.random.randn(1000)
cats = pd.qcut(data, 4)
cats

[(-3.033, -0.627], (0.675, 3.238], (0.0447, 0.675], (-0.627, 0.0447], (-3.033, -0.627], ..., (-0.627, 0.0447], (0.0447, 0.675], (0.0447, 0.675], (0.675, 3.238], (-3.033, -0.627]]
Length: 1000
Categories (4, interval[float64]): [(-3.033, -0.627] < (-0.627, 0.0447] < (0.0447, 0.675] < (0.675, 3.238]]

In [41]:
pd.value_counts(cats)

(0.675, 3.238]      250
(0.0447, 0.675]     250
(-0.627, 0.0447]    250
(-3.033, -0.627]    250
dtype: int64

In [42]:
cats2 = pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

In [43]:
cats2

[(-1.296, 0.0447], (0.0447, 1.267], (0.0447, 1.267], (-1.296, 0.0447], (-1.296, 0.0447], ..., (-1.296, 0.0447], (0.0447, 1.267], (0.0447, 1.267], (1.267, 3.238], (-3.033, -1.296]]
Length: 1000
Categories (4, interval[float64]): [(-3.033, -1.296] < (-1.296, 0.0447] < (0.0447, 1.267] < (1.267, 3.238]]

In [45]:
pd.value_counts(cats2)

(0.0447, 1.267]     400
(-1.296, 0.0447]    400
(1.267, 3.238]      100
(-3.033, -1.296]    100
dtype: int64

In [46]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [47]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.005015    -0.029891    -0.011698     0.012634
std       0.965900     1.036207     0.993898     0.997373
min      -3.207963    -3.108604    -3.298824    -3.124201
25%      -0.646766    -0.745580    -0.701154    -0.682402
50%      -0.031607    -0.054192    -0.033011    -0.017431
75%       0.621344     0.683392     0.650516     0.713254
max       3.352223     2.855956     2.894300     2.938952

In [48]:
col = data[2]

In [49]:
col

0      0.009021
1      0.598329
2      0.087347
3     -1.124737
4     -0.770420
         ...   
995    0.364190
996    0.459077
997    0.108094
998   -0.085728
999    2.092225
Name: 2, Length: 1000, dtype: float64

In [52]:
data.shape

(1000, 4)

In [53]:
col[np.abs(col) > 3]

367   -3.298824
Name: 2, dtype: float64

In [54]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
1    3.352223  1.233111  0.598329 -0.054727
284 -0.192241 -0.607299  1.363852 -3.124201
367  0.767624 -1.733735 -3.298824  0.133724
371 -3.207963 -0.646314  1.351591 -1.045736
569  0.554747 -3.108604  0.766924  0.004759
630 -1.288655 -3.079635  1.025987  0.656979
799 -2.141919 -0.274285 -1.469848 -3.064700

In [55]:
data[(np.abs(data) > 3)]

0   1   2   3
0         NaN NaN NaN NaN
1    3.352223 NaN NaN NaN
2         NaN NaN NaN NaN
3         NaN NaN NaN NaN
4         NaN NaN NaN NaN
..        ...  ..  ..  ..
995       NaN NaN NaN NaN
996       NaN NaN NaN NaN
997       NaN NaN NaN NaN
998       NaN NaN NaN NaN
999       NaN NaN NaN NaN

[1000 rows x 4 columns]

In [59]:
(np.abs(data) > 3).any(axis=1)

0      False
1       True
2      False
3      False
4      False
       ...  
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [60]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [61]:
data

0         1         2         3
0    0.166292  0.714986  0.009021 -0.793171
1    3.000000  1.233111  0.598329 -0.054727
2   -0.202432  1.485923  0.087347 -0.397516
3    0.678068  0.424544 -1.124737 -0.386901
4   -0.985069  0.480818 -0.770420 -1.798734
..        ...       ...       ...       ...
995  0.551462 -0.677430  0.364190 -1.059742
996  0.430294 -0.988969  0.459077  0.142631
997  2.435474 -0.254526  0.108094 -1.334367
998  0.720932  1.776387 -0.085728 -0.226996
999  0.424589 -1.134882  2.092225 -0.440696

[1000 rows x 4 columns]

In [62]:
df = pd.DataFrame(np.arange(5*4).reshape((5, 4)))

In [63]:
sampler = np.random.permutation(5)
sampler

array([1, 4, 3, 2, 0])

In [64]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [66]:
np.random.permutation(5)

array([4, 1, 0, 2, 3])

In [67]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
4  16  17  18  19
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3

In [68]:
df.sample(n=3)

0   1   2   3
2   8   9  10  11
4  16  17  18  19
3  12  13  14  15

In [69]:
choices = pd.Series([5, 7, -1, 6, 4])

In [70]:
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [71]:
draws = choices.sample(n=10, replace=True)

In [72]:
draws

0    5
0    5
2   -1
3    6
2   -1
0    5
1    7
3    6
4    4
4    4
dtype: int64

In [73]:
pd.value_counts(draws)

 5    3
 6    2
 4    2
-1    2
 7    1
dtype: int64

In [74]:
pd.value_counts(choices)

 7    1
 6    1
 5    1
 4    1
-1    1
dtype: int64

In [75]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                    'data1': range(6)})

In [76]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [77]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [83]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [84]:
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [79]:
df_with_dummy = df[['data1']].join(dummies)

In [80]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [81]:
df['data1']

0    0
1    1
2    2
3    3
4    4
5    5
Name: data1, dtype: int64

In [82]:
df[['data1']]

data1
0      0
1      1
2      2
3      3
4      4
5      5

In [3]:
mnames = ['movie_id', 'title', 'genres']

In [5]:
movies = pd.read_csv('datasets/movielens/movies.dat', sep='::', header=None, names=mnames)

/home/bird/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [6]:
movies.shape

(3883, 3)

In [11]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [17]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [18]:
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [19]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [20]:
dummies = pd.DataFrame(zero_matrix, columns = genres)
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
1           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
2           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
4           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    0.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [21]:
gen = movies.genres[0]

In [23]:
gen

"Animation|Children's|Comedy"

In [33]:
type(movies.genres)

pandas.core.series.Series

In [24]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [25]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [26]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [27]:
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           1.0         1.0     1.0        0.0      0.0      0.0    0.0   
1           0.0         1.0     0.0        1.0      1.0      0.0    0.0   
2           0.0         0.0     1.0        0.0      0.0      1.0    0.0   
3           0.0         0.0     1.0        0.0      0.0      0.0    1.0   
4           0.0         0.0     1.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     1.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    1.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       1.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [29]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [32]:
movies_windic[:10]

movie_id                               title                        genres  \
0         1                    Toy Story (1995)   Animation|Children's|Comedy   
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy   
2         3             Grumpier Old Men (1995)                Comedy|Romance   
3         4            Waiting to Exhale (1995)                  Comedy|Drama   
4         5  Father of the Bride Part II (1995)                        Comedy   
5         6                         Heat (1995)         Action|Crime|Thriller   
6         7                      Sabrina (1995)                Comedy|Romance   
7         8                 Tom and Huck (1995)          Adventure|Children's   
8         9                 Sudden Death (1995)                        Action   
9        10                    GoldenEye (1995)     Action|Adventure|Thriller   

   Genre_Animation  Genre_Children's  Genre_Comedy  Genre_Adventure  \
0              1.0               1.0           1.0              0.0   
1              0.0               1.0           0.0              1.0   
2              0.0               0.0           1.0              0.0   
3              0.0               0.0           1.0              0.0   
4              0.0               0.0           1.0              0.0   
5              0.0               0.0           0.0              0.0   
6              0.0               0.0           1.0              0.0   
7              0.0               1.0           0.0              1.0   
8              0.0               0.0           0.0              0.0   
9              0.0               0.0           0.0              1.0   

   Genre_Fantasy  Genre_Romance  Genre_Drama  ...  Genre_Crime  \
0            0.0            0.0          0.0  ...          0.0   
1            1.0            0.0          0.0  ...          0.0   
2            0.0            1.0          0.0  ...          0.0   
3            0.0            0.0          1.0  ...          0.0   
4            0.0            0.0          0.0  ...          0.0   
5            0.0            0.0          0.0  ...          1.0   
6            0.0            1.0          0.0  ...          0.0   
7            0.0            0.0          0.0  ...          0.0   
8            0.0            0.0          0.0  ...          0.0   
9            0.0            0.0          0.0  ...          0.0   

   Genre_Thriller  Genre_Horror  Genre_Sci-Fi  Genre_Documentary  Genre_War  \
0             0.0           0.0           0.0                0.0        0.0   
1             0.0           0.0           0.0                0.0        0.0   
2             0.0           0.0           0.0                0.0        0.0   
3             0.0           0.0           0.0                0.0        0.0   
4             0.0           0.0           0.0                0.0        0.0   
5             1.0           0.0           0.0                0.0        0.0   
6             0.0           0.0           0.0                0.0        0.0   
7             0.0           0.0           0.0                0.0        0.0   
8             0.0           0.0           0.0                0.0        0.0   
9             1.0           0.0           0.0                0.0        0.0   

   Genre_Musical  Genre_Mystery  Genre_Film-Noir  Genre_Western  
0            0.0            0.0              0.0            0.0  
1            0.0            0.0              0.0            0.0  
2            0.0            0.0              0.0            0.0  
3            0.0            0.0              0.0            0.0  
4            0.0            0.0              0.0            0.0  
5            0.0            0.0              0.0            0.0  
6            0.0            0.0              0.0            0.0  
7            0.0            0.0              0.0            0.0  
8            0.0            0.0              0.0            0.0  
9            0.0            0.0              0.0            0.0  

[10 r

In [34]:
np.random.seed(12345)

In [35]:
values = np.random.rand(10)

In [36]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [37]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [39]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0